FROM node:20-alpine AS builder

WORKDIR /app

RUN npm install -g pnpm

COPY package.json pnpm-workspace.yaml ./
COPY packages/prisma/package.json ./packages/prisma/
COPY apps/web/package.json ./apps/web/

RUN pnpm install --frozen-lockfile

COPY . .

RUN pnpm db:generate
RUN cd apps/web && pnpm build

FROM node:20-alpine AS runner

WORKDIR /app

ENV NODE_ENV production

RUN npm install -g pnpm

COPY package.json pnpm-workspace.yaml ./
COPY packages/prisma/package.json ./packages/prisma/
COPY apps/web/package.json ./apps/web/

RUN pnpm install --prod --frozen-lockfile

COPY --from=builder /app/apps/web/.next ./apps/web/.next
COPY --from=builder /app/apps/web/public ./apps/web/public
COPY --from=builder /app/apps/web/package.json ./apps/web/

WORKDIR /app/apps/web

EXPOSE 3000

ENV PORT 3000
ENV HOSTNAME "0.0.0.0"

CMD ["pnpm", "start"]

